### ISSUE TITLE
Can't read files open by another process

### ISSUE THREAD

**Issue by JoshDavid** [the-carlisle-group/XL2APL#11]
Hey TCG, happy holidays!

The function XL2APL.Main.OpenExcelFile uses the .NET ZipFile.OpenRead method to read in a .NET ZipArchive. One shortcoming of this method is that it will fail if the file is open by another process. The owner of this other process could yourself, or even some other user if you're trying to open an Excel file that is located on a shared network drive. This latter situation can be a pretty common occurrence in a corporate environment. Reading from the COM Interop (with ⎕WC 'OleClient' 'Excel.application'... ) does not have this problem. So this is a pretty big showstopper for users who have been using COM to read Excel files.

After investigating further, I was surprised to find that the ZipFile.OpenRead method is not opening the file in ReadOnly mode. Some might be tempted to trap the exception, ⎕NCOPY the file into a temp dir, work on that, then delete it. But that can lead to a lot of problems + greatly increases the code complexity and liability. A much cleaner way to get around this is to create your own FileStream where you explicitly ask to open in ReadOnly mode. I am proposing to change the XL2APL.Main.OpenExcelFile function to something like:

<code>
OpenExcelFile←{ 

     ⍝ ⍵ ←→ File Name 
     ⍝ ← ←→ .NET ZipArchive 
     ⎕USING←'System.IO.Compression,System.IO.Compression.dll' 
     ⎕USING,←⊂'System.IO,System.Runtime.dll' ⍝ For FileStreams 
     fs ← ⎕NEW FileStream(⍵ FileMode.Open FileAccess.Read FileShare.ReadWrite) 
     ⎕NEW ZipArchive(fs ZipArchiveMode.Read) 

 }
</code>

This way, you can open and read Excel files even if someone else has it open in ReadOnly mode. 

I think this is actually a pretty important fix. Many developers might not run into this problem, but I'm sure clients will hit this problem of shared Excel files before most developers do!

I haven't done much testing of this with files located on a network. I will have to do that. It would be interesting to start doing some timing benchmarks and seeing if there is a lot of time involved in running the OpenExcelFile on network files, because that can get called a few times in the process of retrieving a workbook (maybe some redundancy can be removed by opening once and passing some arguments down?). I'd have to read up on the method more, but that's just a thought I had and maybe I'll make a separate thread if I get to experiment some more.

Regards,
Josh

**Comment by PaulMansour** [comment]
Hi Josh. Thanks very much for the detailed report and solution. I will play around with it, write a test or two, and put it  it in. Thanks again.

**Comment by PaulMansour** [comment]
Fixed. Thanks again Josh for reporting and solving problem.
